# Generated by Django 4.1.5 on 2023-02-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desarrolladoras', '0001_initial'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_lanzamiento', models.DateTimeField()),
                ('valoracion_estrellas', models.CharField(max_length=30)),
                ('desarrolladora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrolladoras.desarrolladora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
        ),
    ]
